source "https://rubygems.org"
ruby "3.4.0"

gem "rails", "~> 8.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.0"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[windows jruby]

# Auth
gem "jwt", "~> 2.9"
gem "aws-sdk-cognitoidentityprovider", "~> 1.100"

# Serialization
gem "alba", "~> 3.3"

# Background Jobs
gem "sidekiq", "~> 7.3"
gem "sidekiq-pro", source: "https://gems.contribsys.com/" if ENV["SIDEKIQ_PRO_KEY"]

# Multi-tenancy infrastructure
gem "apartment", "~> 2.3"
gem "connection_pool", "~> 2.4"

# Observability
gem "opentelemetry-sdk"
gem "opentelemetry-exporter-otlp"
gem "opentelemetry-instrumentation-rails"
gem "opentelemetry-instrumentation-active_record"
gem "opentelemetry-instrumentation-pg"

# Config
gem "dry-configurable", "~> 1.2"
gem "dry-validation", "~> 1.10"
gem "dry-monads", "~> 1.6"

# Pagination
gem "pagy", "~> 9.0"

# Rate limiting
gem "rack-attack", "~> 6.7"

# Health check
gem "rails-healthcheck", "~> 1.4"

group :development, :test do
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.3"
  gem "pry-byebug"
  gem "dotenv-rails"
end

group :test do
  gem "shoulda-matchers", "~> 6.2"
  gem "database_cleaner-active_record", "~> 2.2"
  gem "webmock", "~> 3.23"
  gem "timecop", "~> 0.9"
  gem "simplecov", require: false
  gem "simplecov-lcov", require: false
  gem "rspec-sidekiq", "~> 5.0"
  gem "dry-monads-rspec", "~> 0.1"
end
