apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wildcard-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "*.${MINIKUBE_IP}.nip.io"    # <- 後述の手順で置換
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gui-service
            port: { number: 80 }
