apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-dev-server
  namespace: default
# automountServiceAccountToken: false により、
# Kubernetes APIへのアクセスが不要なこのアプリケーションに
# 不要なService Account Tokenが自動マウントされないようにする。
automountServiceAccountToken: false
